-- NiLaundry schema (PostgreSQL).
-- All PKs use GENERATED BY DEFAULT AS IDENTITY (PG SERIAL equivalent) so we
-- never need MAX(id)+1 in application code and avoid race conditions.

BEGIN;

DROP TABLE IF EXISTS pesanan_notifikasi CASCADE;
DROP TABLE IF EXISTS notifikasi_pelanggan CASCADE;
DROP TABLE IF EXISTS voucher_pelanggan CASCADE;
DROP TABLE IF EXISTS ulasan CASCADE;
DROP TABLE IF EXISTS pembayaran CASCADE;
DROP TABLE IF EXISTS pengiriman CASCADE;
DROP TABLE IF EXISTS item_pesanan CASCADE;
DROP TABLE IF EXISTS pesanan CASCADE;
DROP TABLE IF EXISTS notifikasi CASCADE;
DROP TABLE IF EXISTS voucher CASCADE;
DROP TABLE IF EXISTS tarif CASCADE;
DROP TABLE IF EXISTS layanan CASCADE;
DROP TABLE IF EXISTS pegawai CASCADE;
DROP TABLE IF EXISTS kurir CASCADE;
DROP TABLE IF EXISTS tipe_kendaraan CASCADE;
DROP TABLE IF EXISTS pengguna CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS pelanggan CASCADE;
DROP TABLE IF EXISTS cabang_laundry CASCADE;

-- role: lookup table for non-customer roles (superadmin, admin).
-- Customers (pelanggan) are not in this table; their role is implicit.
CREATE TABLE role (
    id_role   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_role VARCHAR(32) NOT NULL UNIQUE
);

-- cabang_laundry (declared before pengguna so pengguna can FK it)
CREATE TABLE cabang_laundry (
    id_cabang        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_cabang      VARCHAR(255) NOT NULL,
    alamat_cabang    TEXT NOT NULL,
    no_telp_cabang   VARCHAR(32) NOT NULL,
    jam_buka_cabang  TIME NOT NULL,
    jam_tutup_cabang TIME NOT NULL
);

-- pelanggan
CREATE TABLE pelanggan (
    id_pelanggan       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pelanggan     VARCHAR(255) NOT NULL,
    password_pelanggan VARCHAR(255) NOT NULL,
    email_pelanggan    VARCHAR(255) NOT NULL UNIQUE,
    no_telp_pelanggan  VARCHAR(32) NOT NULL,
    alamat_pelanggan   TEXT NOT NULL
);

-- pengguna: backoffice users (superadmin / admin). Customer login still
-- goes through `pelanggan`. Schema deliberately mirrors `pelanggan` so the
-- auth flow (email + bcrypt password) is identical.
-- cabang_laundry_id_cabang is NULL for superadmin (sees all branches) and
-- NOT NULL for admin (scoped to one branch).
CREATE TABLE pengguna (
    id_pengguna              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pengguna            VARCHAR(255) NOT NULL,
    email_pengguna           VARCHAR(255) NOT NULL UNIQUE,
    password_pengguna        VARCHAR(255) NOT NULL,
    role_id_role             INT NOT NULL REFERENCES role(id_role),
    cabang_laundry_id_cabang INT REFERENCES cabang_laundry(id_cabang)
);


-- pegawai
CREATE TABLE pegawai (
    id_pegawai              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pegawai            VARCHAR(255) NOT NULL,
    email_pegawai           VARCHAR(255) NOT NULL,
    no_telp_pegawai         VARCHAR(32) NOT NULL,
    alamat_pegawai          TEXT NOT NULL,
    cabang_laundry_id_cabang INT NOT NULL REFERENCES cabang_laundry(id_cabang)
);

-- layanan
CREATE TABLE layanan (
    id_layanan        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_layanan      VARCHAR(255) NOT NULL,
    satuan_layanan    VARCHAR(64)  NOT NULL,
    deskripsi_layanan TEXT
);

-- tarif
CREATE TABLE tarif (
    id_tarif                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harga_per_satuan          NUMERIC(12,2) NOT NULL,
    cabang_laundry_id_cabang  INT NOT NULL REFERENCES cabang_laundry(id_cabang),
    layanan_id_layanan        INT NOT NULL REFERENCES layanan(id_layanan)
);

-- voucher
CREATE TABLE voucher (
    id_voucher             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_voucher           VARCHAR(64) NOT NULL UNIQUE,
    tipe_diskon_voucher    VARCHAR(32) NOT NULL,
    nilai_diskon_voucher   NUMERIC(12,2) NOT NULL,
    min_pembelian_voucher  NUMERIC(12,2) NOT NULL,
    berlaku_hingga_voucher TIMESTAMP NOT NULL,
    kuota_voucher          INT NOT NULL,
    terpakai_voucher       INT NOT NULL DEFAULT 0
);

CREATE TABLE voucher_pelanggan (
    voucher_id_voucher    INT NOT NULL REFERENCES voucher(id_voucher),
    pelanggan_id_pelanggan INT NOT NULL REFERENCES pelanggan(id_pelanggan),
    PRIMARY KEY (voucher_id_voucher, pelanggan_id_pelanggan)
);

-- pesanan
CREATE TABLE pesanan (
    id_pesanan               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jumlah_item_pesanan      INT NOT NULL,
    status_pesanan           VARCHAR(64) NOT NULL,
    catatan_pesanan          TEXT NOT NULL DEFAULT '',
    estimasi_selesai_pesanan TIMESTAMP NOT NULL,
    total_harga_pesanan      NUMERIC(12,2) NOT NULL,
    pelanggan_id_pelanggan   INT NOT NULL REFERENCES pelanggan(id_pelanggan),
    voucher_id_voucher       INT REFERENCES voucher(id_voucher),
    pegawai_id_pegawai       INT NOT NULL REFERENCES pegawai(id_pegawai),
    -- Delivery scenario: how the laundry is sent in / returned.
    jenis_ambil              VARCHAR(16) NOT NULL DEFAULT 'pickup',   -- 'pickup' | 'walkin'
    jenis_antar              VARCHAR(16) NOT NULL DEFAULT 'delivery'  -- 'delivery' | 'walkin'
);

CREATE TABLE pesanan_notifikasi (
    pesanan_id_pesanan       INT NOT NULL,
    notifikasi_id_notifikasi INT NOT NULL,
    CONSTRAINT pesanan_notifikasi_pk PRIMARY KEY (pesanan_id_pesanan, notifikasi_id_notifikasi)
);

-- item_pesanan
CREATE TABLE item_pesanan (
    id_item_pesanan              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kuantitas_satuan_item_pesanan INT NOT NULL,
    subtotal_pesanan             NUMERIC(12,2) NOT NULL,
    catatan_item_pesanan         TEXT,
    pesanan_id_pesanan           INT NOT NULL REFERENCES pesanan(id_pesanan) ON DELETE CASCADE,
    tarif_id_tarif               INT NOT NULL REFERENCES tarif(id_tarif)
);

-- pembayaran
CREATE TABLE pembayaran (
    id_pembayaran      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    waktu_pembayaran   TIMESTAMP NOT NULL,
    metode_pembayaran  VARCHAR(64) NOT NULL,
    status_pembayaran  VARCHAR(32) NOT NULL,
    jumlah_pembayaran  NUMERIC(12,2) NOT NULL,
    pesanan_id_pesanan INT NOT NULL REFERENCES pesanan(id_pesanan)
);

-- Table: tipe_kendaraan
CREATE TABLE tipe_kendaraan (
    id_kendaraan int  NOT NULL,
    jenis_kendaraan Varchar  NOT NULL,
    CONSTRAINT tipe_kendaraan_pk PRIMARY KEY (id_kendaraan)
);

CREATE TABLE kurir (
    id_kurir int  NOT NULL,
    nama_kurir Varchar  NOT NULL,
    no_telp_kurir Varchar  NOT NULL,
    no_plat_kurir Varchar  NOT NULL,
    tipe_kendaraan_id_kendaraan int  NOT NULL,
    CONSTRAINT kurir_pk PRIMARY KEY (id_kurir)
);

CREATE TABLE pengiriman (
    id_pengiriman int  NOT NULL,
    waktu_pengiriman TIMESTAMP  NOT NULL,
    jenis_pengiriman Varchar  NOT NULL,
    alamat_pengiriman Text  NOT NULL,
    status_pengiriman Varchar  NOT NULL,
    ongkir_pengiriman Decimal  NOT NULL,
    bukti_pengiriman Text  NOT NULL,
    pesanan_id_pesanan int  NOT NULL,
    kurir_id_kurir int  NOT NULL,
    CONSTRAINT pengiriman_pk PRIMARY KEY (id_pengiriman)
);

-- notifikasi
CREATE TABLE notifikasi (
    id_notifikasi    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul_notifikasi VARCHAR(255) NOT NULL,
    pesan_notifikasi TEXT NOT NULL,
    tipe_notifikasi  VARCHAR(64) NOT NULL
);

CREATE TABLE notifikasi_pelanggan (
    notifikasi_id_notifikasi INT NOT NULL REFERENCES notifikasi(id_notifikasi),
    pelanggan_id_pelanggan   INT NOT NULL REFERENCES pelanggan(id_pelanggan),
    PRIMARY KEY (notifikasi_id_notifikasi, pelanggan_id_pelanggan)
);

-- ulasan
CREATE TABLE ulasan (
    id_ulasan        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_ulasan    INT NOT NULL CHECK (rating_ulasan BETWEEN 1 AND 5),
    komentar_ulasan  TEXT NOT NULL,
    waktu_ulasan  TIMESTAMP  NOT NULL,
    pesanan_id_pesanan INT NOT NULL REFERENCES pesanan(id_pesanan)
);

COMMIT;
